// app/page.tsx
// This file maps to the index route (/)
export default function Page() {
  return (
    <div className="mx-auto" style={{maxWidth: '42rem'}}>
    <h1>Welcome to my page</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, augue eget feugiat iaculis, quam ipsum auctor metus, non molestie ipsum metus sit amet quam. Sed malesuada, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh eget est. Sed in risus eget nulla convallis dictum id in augue. Sed auctor, augue euismod malesuada porta, orci nulla interdum ligula, at rutrum magna nibh e
    </p>
  </div>
  )
}